project_name: rag-s3vector

naming:
  prefix: cits
  suffix: ""
  unique_id: cits001

bedrock:
  embedding_model_id: "amazon.nova-2-multimodal-embeddings-v1:0"
  llm_model_id: "us.meta.llama3-3-70b-instruct-v1:0"
  vector_dimension: 1024

lambda:
  runtime: "PYTHON_3_12"
  handler: "handler.lambda_handler"
  ingestion:
    timeout_minutes: 5
    memory_size: 512
    code_path: "../app/ingestion"
  query:
    timeout_minutes: 1
    memory_size: 256
    code_path: "../app/query"

fargate:
  cpu: 256
  memory: 512
  desired_count: 1
  container_port: 8000

tags:
  APP: rag
  ENV: dev
  ORG: CITS
